######################################################################
# Automatically generated by qmake (2.01a) Sun Jul 8 17:35:24 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += canvas.h mainwindow.h
FORMS += mainwindow.ui
SOURCES += canvas.cpp main.cpp mainwindow.cpp

CONFIG += debug
QT += xml
